INSERT INTO VEHICLE (ID, NAME, PRICE, SHOP_ID) VALUES (1, 'benz', 1000, 1)
INSERT INTO VEHICLE (ID, NAME, PRICE, SHOP_ID) VALUES (2, 'mar', 2000, 1)
INSERT INTO VEHICLE (ID, NAME, PRICE, SHOP_ID) VALUES (3, 'juz', 3000, 2)
INSERT INTO VEHICLE (ID, NAME, PRICE, SHOP_ID) VALUES (4, 'zha', 4000, 3)
