version: '2'
services:
    eureka-server:
        image: eureka-server
        container_name: eureka-server-container
        ports:
            - "8761:8761"
    config-server:
        image: config-server
        container_name: config-server-container
        ports:
            - "1201:1201"
        depends_on:
          - "eureka-server"
        command: ["/apps/wait-for-it.sh", "eureka-server-container:8761","-t", "60", "--", "/bin/sh", "./run.sh" ]
    eureka-client:
        image: eureka-client
        container_name: eureka-client-container
        ports:
            - "8762:8762"
        depends_on:
            - "config-server"
        command: ["/apps/wait-for-it.sh", "config-server-container:1201", "-t", "60", "--", "/bin/sh", "./run.sh" ]
    service-order:
        image: service-order
        container_name: service-order-container
        ports:
            - "8763:8763"
        depends_on:
            - "config-server"
        command: ["/apps/wait-for-it.sh", "config-server-container:1201", "-t", "60", "--", "/bin/sh", "./run.sh" ]
    service-vehicle:
        image: service-vehicle
        container_name: service-vehicle-container
        ports:
            - "8764:8764"
        depends_on:
            - "config-server"
        command: ["/apps/wait-for-it.sh", "config-server-container:1201", "-t", "60", "--", "/bin/sh", "./run.sh" ]
    bff:
        image: bff
        container_name: bff-container
        ports:
            - "8765:8765"
        depends_on:
            - "config-server"
        command: ["/apps/wait-for-it.sh", "config-server-container:1201", "-t", "60", "--", "/bin/sh", "./run.sh" ]
    api-gateway:
        image: api-gateway
        container_name: api-gateway-container
        ports:
            - "1101:1101"
        depends_on:
            - "config-server"
        command: ["/apps/wait-for-it.sh", "config-server-container:1201", "-t", "60", "--", "/bin/sh", "./run.sh" ]
networks:
    default:
        external:
            name: microservice
