spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

server:
  port: 1101
  tomcat:
    max-threads: 128 # 最大worker线程
    min-spare-threads: 64 # 最小worker线程
  undertow:
    io-threads: 8 # IO线程数，默认为CPU核心数，最小为2
    worker-threads: 40 # 阻塞任务线程池，值设置取决于系统的负载，默认为io-threads * 8
    buffer-size: 512 # 每块buffer的空间大小
    direct-buffers: false # 是否分配的直接内存

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5

api:
  security:
    paths: /**
    roles: ADMIN
    users:
      username: password,ROLE_ADMIN,enabled
zuul:
  host:
    max-total-connections: 500
    max-per-route-connections: 50
  ribbon-isolation-strategy: thread

---
spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin-server-container:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-container:8761/eureka