INSERT INTO SHOP (ID, CODE, NAME) VALUES (1, 'code1', 'name1')
INSERT INTO SHOP (ID, CODE, NAME) VALUES (2, 'code2', 'name2')

INSERT INTO VEHICLE_ORDER (ID, VEHICLE, PRICE, SHOP_ID) VALUES (1, 'benz', 99, 1)
INSERT INTO VEHICLE_ORDER (ID, VEHICLE, PRICE, SHOP_ID) VALUES (2, 'mar', 100, 1)
INSERT INTO VEHICLE_ORDER (ID, VEHICLE, PRICE, SHOP_ID) VALUES (3, 'test', 200, 1)
INSERT INTO VEHICLE_ORDER (ID, VEHICLE, PRICE, SHOP_ID) VALUES (4, 'Juz', 300, 2)
INSERT INTO VEHICLE_ORDER (ID, VEHICLE, PRICE, SHOP_ID) VALUES (5, 'Nib', 100, 2)