spring:
  application:
    name: zipkin-server

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-container:8761/eureka