server:
  port: 8765

spring:
  application:
    name: bff

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  file: /apps/boot/application.log

service:
  order:
    url: "http://localhost"
    port: 8763
    timeout: 2000
  vehicle:
    url: "http://localhost"
    port: 8764
    timeout: 2000
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-container:8761/eureka

