spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/xuyao/IdeaProjects/microservice
          search-paths: '/config-data/{application}/{profile}'

server:
  port: 1201

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ndrlslz/micro-service
          search-paths: '/config-data/{application}/{profile}'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-container:8761/eureka