server:
  port: 8763

spring:
  application:
    name: service-order
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
eureka:
  client:
    enabled: false

logging:
  file: /apps/boot/application.log