server:
  port: 8763

spring:
  application:
    name: service-order
  datasource:
    url: jdbc:h2:file:/tmp/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MV_STORE=FALSE;MVCC=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    enabled: false


logging:
  file: /apps/boot/application.log