server:
  port: 8763

spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/order?useSSL=false
    username: root
    password: passw0rd
  jpa:
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  path: service-order/build/logs

---
spring:
  profiles: docker
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://service-order-db-container:3306/order?useSSL=false
    username: root
    password: passw0rd
  zipkin:
    base-url: http://zipkin-server-container:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-container:8761/eureka

