server:
  port: 8764

spring:
  application:
    name: service-vehicle
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/vehicle?useSSL=false
    username: root
    password: passw0rd
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  file: /apps/boot/application.log

